import { BlenderArea } from '../app/util/enums/blender-area.enum';
import { BlenderShortcuts } from '../app/util/interfaces/blender-shortcuts.interface';

export const shortcuts: BlenderShortcuts[] = [
  //Edit
  {
    area: [BlenderArea.EditMode],
    title: 'Moving',
    shortcut: 'G',
    description: ['Move selected object around'],
    information: ['+X/Y/Z: move along axis', 'no need to click, just select'],
    tags: ['move'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'Rotating',
    shortcut: 'R',
    description: ['Rotate selected object'],
    information: ['+X/Y/Z: rotate around axis'],
    tags: ['rotate'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'Scaling',
    shortcut: 'S',
    description: ['Scale selected object'],
    information: ['+X/Y/Z: scale along axis'],
    tags: ['scale'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'Triangles to Quads',
    shortcut: 'Alt J',
    description: ['Triangles to Quads'],
    information: ['can only be two, less/more wont work'],
    tags: ['triangles', 'quads'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'extruding options',
    shortcut: 'Alt E',
    description: ['Options for Extruding'],
    information: [],
    tags: ['extrude'],
  },

  //General
  {
    area: [BlenderArea.General],
    title: 'Common Shortcuts',
    shortcut: '⇧ ␣',
    description: ['Open Menu for common Shortcuts'],
    information: [],
    tags: ['menu', 'common'],
  },
  {
    area: [BlenderArea.General],
    title: 'Quick Favorites',
    shortcut: 'Q',
    description: ['Open Menu to quickly access favorite actions'],
    information: ['You can add them by ...'],
    tags: ['menu', 'favorite'],
  },
  {
    area: [BlenderArea.General],
    title: 'Orbit around Object',
    shortcut: 'Middle Mouse',
    description: ['Orbit around an selected object'],
    information: [],
    tags: ['view', 'viewport', 'orbit'],
  },
  {
    area: [BlenderArea.General],
    title: 'Move Viewport around',
    shortcut: '⇧ Middle Mouse',
    description: ['Orbit around an selected object'],
    information: [],
    tags: ['view', 'viewport', 'move'],
  },
  {
    area: [BlenderArea.General],
    title: 'Zoom Viewport',
    shortcut: 'Scroll Middle Mouse',
    description: ['Zoom on an selected object'],
    information: [],
    tags: ['view', 'viewport', 'zoom'],
  },
  {
    area: [BlenderArea.General],
    title: 'Viewport to selected',
    shortcut: 'Numpad .',
    description: ['Move Viewport to selected'],
    information: [],
    tags: ['view', 'viewport', 'selected'],
  },
  {
    area: [BlenderArea.General],
    title: 'Plain Front View',
    shortcut: 'Numpad 1',
    description: ['Viewport to Front View (Plain)'],
    information: [],
    tags: ['view', 'viewport', 'front'],
  },
  {
    area: [BlenderArea.General],
    title: 'Plain Side View',
    shortcut: 'Numpad 3',
    description: ['Viewport to Side View (Plain)'],
    information: [],
    tags: ['view', 'viewport', 'side'],
  },
  {
    area: [BlenderArea.General],
    title: 'Plain Top View',
    shortcut: 'Numpad 7',
    description: ['Viewport to Top View (Plain)'],
    information: [],
    tags: ['view', 'viewport', 'top'],
  },
  {
    area: [BlenderArea.General],
    title: 'Perspective Mode',
    shortcut: 'Numpad 5',
    description: ['Enable/Disabled Perspective Mode'],
    information: [],
    tags: ['perspective'],
  },
  {
    area: [BlenderArea.General],
    title: 'Delete selected',
    shortcut: 'X',
    description: ['Delete selected'],
    information: [],
    tags: ['delete'],
  },
  {
    area: [BlenderArea.General],
    title: 'Relocate selected to center',
    shortcut: 'Alt G',
    description: ['Relocate selected to center'],
    information: [],
    tags: ['relocate', 'center'],
  },
  {
    area: [BlenderArea.General],
    title: 'menu for adding Objects',
    shortcut: '⇧ A',
    description: ['menu for adding Objects'],
    information: [],
    tags: ['menu', 'adding', 'objects'],
  },
  {
    area: [BlenderArea.General],
    title: 'last action',
    shortcut: 'F9',
    description: ['Bring back last action'],
    information: [],
    tags: ['menu', 'action'],
  },
  {
    area: [BlenderArea.General],
    title: 'show/hide side options/properties',
    shortcut: 'N',
    description: ['show/hide side options/properties'],
    information: [],
    tags: ['options', 'properties'],
  },
  {
    area: [BlenderArea.General],
    title: 'Apply',
    shortcut: 'Ctrl A',
    description: ['Apply ...'],
    information: ['Its possible to apply scale for scale, transform ...'],
    tags: ['apply'],
  },
  {
    area: [BlenderArea.General],
    title: 'Pie Menu',
    shortcut: 'Ctrl Tab',
    description: ['Open Object Pie Menu'],
    information: [],
    tags: ['pie', 'menu'],
  },
];
