import { BlenderArea } from '../app/util/enums/blender-area.enum';
import { BlenderShortcuts } from '../app/util/interfaces/blender-shortcuts.interface';

export const editModeShortcuts: BlenderShortcuts[] = [
  {
    area: [BlenderArea.EditMode],
    title: 'Moving',
    shortcut: ['G'],
    description: ['Move selected object around'],
    information: [
      '+X/Y/Z: move along axis',
      'no need to click, just select and drag',
    ],
    tags: ['move'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'Rotating',
    shortcut: ['R'],
    description: ['Rotate selected object'],
    information: ['+X/Y/Z: rotate along axis', 'should be applied'],
    tags: ['rotate'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'Scaling',
    shortcut: ['S'],
    description: ['Scale selected object'],
    information: ['+X/Y/Z: scale along axis', 'should be applied'],
    tags: ['scale'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'Triangles to Quads',
    shortcut: ['Alt', 'J'],
    description: ['Triangles to Quads'],
    information: ['can only be two, less/more wont work'],
    tags: ['triangles', 'quads'],
  },
  {
    area: [BlenderArea.EditMode],
    title: 'extruding options',
    shortcut: ['Alt', 'E'],
    description: ['Options for Extruding'],
    information: [],
    tags: ['extrude'],
  },
];
export const generalShortcuts: BlenderShortcuts[] = [
  {
    area: [BlenderArea.General],
    title: 'Common Shortcuts',
    shortcut: ['⇧', '␣'],
    description: ['Open Menu for common Shortcuts'],
    information: [],
    tags: ['menu', 'common'],
  },
  {
    area: [BlenderArea.General],
    title: 'Quick Favorites',
    shortcut: ['Q'],
    description: ['Open Menu to quickly access favorite actions'],
    information: [
      'add by right clicking on the desired action',
      'works for menu points, modifiers, views etc.',
    ],
    tags: ['menu', 'favorite'],
  },
  {
    area: [BlenderArea.General],
    title: 'Undo',
    shortcut: ['Ctrl', 'Z'],
    description: ['Undo last actions'],
    information: [],
    tags: ['undo'],
  },
  {
    area: [BlenderArea.General],
    title: 'Redo',
    shortcut: ['⇧', 'Ctrl', 'Z'],
    description: ['Redo last actions'],
    information: [],
    tags: ['redo'],
  },
  {
    area: [BlenderArea.General],
    title: 'Orbit view',
    shortcut: ['Click Middle Mouse'],
    description: ['Orbit around the current view'],
    information: ['selected objects will be ignored'],
    tags: ['view', 'viewport', 'orbit'],
  },
  {
    area: [BlenderArea.General],
    title: 'Move View around',
    shortcut: ['⇧', 'Middle Mouse'],
    description: ['Move the view around freely'],
    information: ['independent from selection'],
    tags: ['view', 'viewport', 'move'],
  },
  {
    area: [BlenderArea.General],
    title: 'Zoom Viewport',
    shortcut: ['Scroll Middle Mouse'],
    description: ['Zoom in the view'],
    information: ['independent from selection'],
    tags: ['view', 'viewport', 'zoom'],
  },
  {
    area: [BlenderArea.General],
    title: 'Viewport to selected',
    shortcut: ['. (Numpad)'],
    description: ['Move Viewport to selected object'],
    information: [],
    tags: ['view', 'viewport', 'selected'],
  },
  {
    area: [BlenderArea.General],
    title: 'Plain Front View',
    shortcut: ['1 (Numpad)'],
    description: ['Viewport to Front View (Y, Plain) of selected object'],
    information: [],
    tags: ['view', 'viewport', 'front'],
  },
  {
    area: [BlenderArea.General],
    title: 'Plain Side View',
    shortcut: ['3 (Numpad)'],
    description: ['Viewport to Side View (X, Plain) of selected object'],
    information: [],
    tags: ['view', 'viewport', 'side'],
  },
  {
    area: [BlenderArea.General],
    title: 'Plain Top View',
    shortcut: ['7 (Numpad)'],
    description: ['Viewport to Top View (Z, Plain) of selected object'],
    information: [],
    tags: ['view', 'viewport', 'top'],
  },
  {
    area: [BlenderArea.General],
    title: 'Perspective Mode',
    shortcut: ['5 (Numpad)'],
    description: ['Enable/Disabled Perspective Mode'],
    information: [],
    tags: ['view', 'perspective'],
  },
  {
    area: [BlenderArea.General],
    title: 'Delete selected',
    shortcut: ['X'],
    description: ['Delete selected'],
    information: ['Sometimes confirmation is needed'],
    tags: ['delete'],
  },
  {
    area: [BlenderArea.General],
    title: 'Relocate to center',
    shortcut: ['Alt', 'G'],
    description: ['Relocate selected Object to center'],
    information: ['independent from cursor position'],
    tags: ['relocate', 'center'],
  },
  {
    area: [BlenderArea.General],
    title: 'Menu for adding Objects',
    shortcut: ['⇧', 'A'],
    description: ['Menu for adding Objects (Meshes, Text, Light etc.)'],
    information: ['will always be added at the cursors location'],
    tags: ['menu', 'adding', 'objects'],
  },
  {
    area: [BlenderArea.General],
    title: 'last action',
    shortcut: ['F9'],
    description: ['Bring back last action once'],
    information: ["closing this menu and it's not possible to open it again"],
    tags: ['menu', 'last action'],
  },
  {
    area: [BlenderArea.General],
    title: 'side properties',
    shortcut: ['N'],
    description: ['show/hide side options/properties (right of viewport)'],
    information: [],
    tags: ['options', 'properties'],
  },
  {
    area: [BlenderArea.General],
    title: 'Apply',
    shortcut: ['Ctrl', 'A'],
    description: ['Apply changes'],
    information: ["it's possible to apply scale, rotation etc."],
    tags: ['apply'],
  },
  {
    area: [BlenderArea.General],
    title: 'Mode Pie Menu',
    shortcut: ['Ctrl', 'Tab'],
    description: ['Open Mode Pie Menu (Modes, Paint)'],
    information: [
      "it's also possible to select the desired point by clicking the connected number",
    ],
    tags: ['mode', 'pie', 'menu'],
  },
  {
    area: [BlenderArea.General],
    title: 'Group Objects',
    shortcut: ['M'],
    description: ['Group selected Objects'],
    information: ["actually called 'Collection'"],
    tags: ['group', 'collection'],
  },
  {
    area: [BlenderArea.General],
    title: 'Create Parent Group',
    shortcut: ['Ctrl', 'P'],
    description: ['Create a Parent Group of selected Objects'],
    information: ['active selected Object is the Parent'],
    tags: ['group', 'parent'],
  },
  {
    area: [BlenderArea.General],
    title: 'Cursor to Center',
    shortcut: ['⇧', 'C'],
    description: ['Move the 3D Cursor to center of View'],
    information: [],
    tags: ['cursor', 'center'],
  },
  {
    area: [BlenderArea.General],
    title: 'Snap Pie Menu',
    shortcut: ['⇧', 'S'],
    description: ['Open Snap Pie Menu (Selection, Cursor)'],
    information: [],
    tags: ['selection', 'cursor', 'pie', 'menu'],
  },
];
